name: hamro
description: "Hamro Aawash Grihaa - Hotel Management System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  cloud_firestore: ^6.5.0
  firebase_messaging: ^16.3.0
  firebase_analytics: ^12.4.2
  firebase_crashlytics: ^5.2.3
  firebase_remote_config: ^6.5.2
  google_sign_in: ^7.2.0

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Code Generation
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

  # Navigation
  go_router: ^17.3.0

  # Responsive
  flutter_screenutil: ^5.9.3
  responsive_framework: ^1.5.1

  # Local Storage
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3

  # Network & Images
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  dio: ^5.8.0+1

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  lottie: ^3.3.1
  intl: ^0.20.2
  url_launcher: ^6.3.1
  flutter_rating_bar: ^4.0.1

  # PDF & Invoice
  pdf: ^3.11.3
  printing: ^5.14.2

  # Dependency Injection
  get_it: ^9.2.1

  # Utils
  dartz: ^0.10.1
  logger: ^2.5.0
  connectivity_plus: ^7.1.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  freezed: ^3.2.5
  json_serializable: ^6.9.5
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
